sudo: required
services:
  - docker

before_install:
  - docker build -t paul/react-test -f ./fe/Dockerfile.dev ./fe

script:
  - docker run -e CI=true paul/react-test npm run test a

after_success:
  - docker build -t phat7049/multi-client ./fe
  - docker build -t phat7049/multi-nginx ./nginx
  - docker build -t phat7049/multi-server ./server
  - docker build -t phat7049/multi-worker ./worker
  # Login docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push docker images to docker hub
  - docker push phat7049/multi-client
  - docker push phat7049/multi-nginx
  - docker push phat7049/multi-server
  - docker push phat7049/multi-worker




